import { ClerkProvider } from "@clerk/nextjs";
import { Outfit } from "next/font/google"; // Import Outfit
import "./globals.css";
import { Metadata } from "next";

// Configure Outfit font
const outfit = Outfit({
  variable: "--font-outfit", // Define a CSS variable for Outfit
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.variable} antialiased`} // Apply Outfit font
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}